apiVersion: v1
kind: Pod
metadata:
  name: pingtest01
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  nodeName: node-01
