apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: management
  namespace: default
subjects:
- kind: User
  name: stu 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pointy-haired-boss
  apiGroup: rbac.authorization.k8s.io
