apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-manager
subjects:
- kind: User # Could use "Group" instead
  name: stu
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: watcher
  apiGroup: rbac.authorization.k8s.io
