apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"failing-services"},"name":"failing-services","namespace":"serviceflail"},"spec":{"ports":[{"name":"default","port":80,"protocol":"TCP","targetPort":9876}],"selector":{"app":"failing-services"}}}
    creationTimestamp: "2020-10-09T13:38:22Z"
    labels:
      app: failing-services
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl
      operation: Update
      time: "2020-10-09T13:38:22Z"
    name: failing-services
    namespace: servicefail
    resourceVersion: "702734"
    selfLink: /api/v1/namespaces/serviceflail/services/failing-services
    uid: e9484be8-6656-4786-bd78-534e0dbccbd4
  spec:
    clusterIP: 172.16.3.135
    ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: 9876
    selector:
      app: failing-services
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
