apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: two-pack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: redis
        name: container-2
      - image: nginx
        name: container-1
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: test-team
