- name: Perform an apt update, and install software-properties-common
  apt:
    update_cache: yes
    name: software-properties-common
  become: yes

- name: Add the deadsnakes ppa repository
  apt_repository: 
    repo: ppa:deadsnakes/ppa
    update_cache: yes
  become: yes

- name: Apt install python3.8, python3.8-venv, python3.8-dev, build-essential
  apt: 
    name:
    - python3.8
    - python3.8-venv
    - python3.8-dev
    - python3-pip # hold your nose
    - build-essential
  become: yes
