- name: bchd-k8s-config - setup localhost loadbalancer for kubectl (as admin)
  shell: kubectl config set-cluster {{ cluster_name }} \
         --certificate-authority={{ ca_pem_file }}  \
         --embed-certs=true \
         --server={{ localhost_lb_apiserver_address }}

- name: bchd-k8s-config - setup creds for admin user
  shell: kubectl config set-credentials admin \ 
         --client-certificate={{ admin_pem_file }} \
         --client-key={{ admin_key_file }} \ 

- name: bchd-k8s-config - setup context for the admin user
  shell: kubectl config set-context {{ cluster_name }} 
         --cluster={{ cluster_name }} \
         --user=admin

- name: bchd-k8s-config - setup use-context for the admin user
  shell: kubectl config use-context {{ cluster_name }}

