- template:
    src: "k8s-install-19.sh"
    dest: "/tmp/k8s-install.sh"
  become: True

- name: install k8s pre-reqs
  command: "bash /tmp/k8s-install.sh"
  become: True

- name: Kubeadm init
  command: 'kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket "unix:///run/containerd/containerd.sock" --ignore-preflight-errors=NumCPU --apiserver-cert-extra-sans bchd'
  become: True
  when: inventory_hostname == "bchd"
  ignore_errors: True

- name: setup kubectl config
  command: "mkdir -p /home/student/.kube"
  when: inventory_hostname == "bchd"

- name: setup kubectl config
  command: "sudo cp /etc/kubernetes/admin.conf /home/student/.kube/config"
  when: inventory_hostname == "bchd"

- name: setup kubectl config
  command: "sudo chown student:student /home/student/.kube/config"
  when: inventory_hostname == "bchd"

- name: Starting CNI (Calico)
  command: "kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml"
  when: inventory_hostname == "bchd"

- name: Get join command
  command: "kubeadm token create --print-join-command"
  register: kjoin
  when: inventory_hostname == "bchd"

- name: print join
  debug: var=kjoin.stdout
  when: inventory_hostname == "bchd"

- set_fact:
    join_command: "{{ hostvars['bchd']['kjoin'].stdout }}"

- name: print join again
  debug: var=join_command
  when: inventory_hostname == "bchd"

- name: join nodes
  command: "{{ join_command }}"
  when: inventory_hostname == 'node-01' or inventory_hostname == 'node-02' or inventory_hostname == 'node-03'
  become: True
  ignore_errors: True

- name: Get Metrics Server
  command: wget https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml

- name: Start Metrics Server
  command: kubectl apply -f components.yaml
  when: inventory_hostname == "bchd"

- name: Get other Metrics Server bit
  command: wget https://static.alta3.com/courses/cka/exam/metrics.yml

- name: Start other Metrics Server bit
  command: kubectl apply -f metrics.yml
  when: inventory_hostname == "bchd"

- name: Ingress Controller Setup
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml
  when: inventory_hostname == "bchd"

- name: Baremetal
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml
  when: inventory_hostname == "bchd"
