---
- name: CKA Setup
  hosts: all
  gather_facts: True
  pre_tasks:
  - command: "sudo hostnamectl set-hostname {{ inventory_hostname }}"
  - command: "sudo mkdir -p /opt/cka/answers"
  - command: "sudo chown student:student /opt/cka/answers"
  roles:
## reset the cluster
  - name: kubeadmteardown
## Install kubeadm 1.18 on master-01
  - name: kubeadm1.18
    when: inventory_hostname == 'master-02' # Done, tested
### Install kubeadm 1.18 on master-03
  - name: kubeadm1.19
    when: inventory_hostname == 'master-03' # Done, tested
### Install kubeadm 1.19 on bchd, node-01, node-02, node-03
  - name: kubeadm1.19withNodes
    when: "'k8s' in group_names" # Done, tested
## save etcd backup to /opt/cka/help/restore.backup
  - name: etcdbackup
    when: inventory_hostname == 'master-03' # Done, tested
## bchd
##  # Create ns integration
##  # Create 3 ubuntu pods, label: app=intensive, no cpu processes
##  # Create 3 ubuntu pods, label: app=intensive, low cpu processes
##  # Create 1 ubuntu pods, label: app=intensive, high cpu process 
  - name: cputopper
    when: inventory_hostname == 'bchd' # Done
## Deployment named dragon, 3 replicas
  - name: dragon
    when: inventory_hostname == 'bchd' # Done
##  # Label node-01 "disk=nvme"
  - name: labeler
    when: inventory_hostname == 'bchd' # Done
##  # Deployment,Service named luau. Pod returns a message on port 80 /aloha that prints 'Aloha means "hi"'
  - name: imagepuller
    when: "'k8s' in group_names" # Done
  - name: aloha
    when: inventory_hostname == 'bchd'
  - name: pvmaker
    when: inventory_hostname == 'bchd'
##  # Deployment named deppy
  - name: deppy
    when: inventory_hostname == 'bchd' # Done
##  # Pod that makes some logs, with "file-not-found" error
  - name: filenotfound
    when: inventory_hostname == 'bchd'
  - name: loggy
    when: inventory_hostname == 'bchd'
### systemctl stop kubelet on node-02
  - name: stopkubelet
    when: inventory_hostname == 'node-02' # Done, tested
